// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwqicftrjcwgjtcfinik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cWljZnRyamN3Z2p0Y2ZpbmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDkxODYsImV4cCI6MjA1MzQyNTE4Nn0.tK8y_3uFIp-_uFn6dWR8oB3X1OQPGaPHf-cHHCyvzn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);